# DataFrames

## 1)creating dataframe

In [51]:
import pandas as pd
import numpy as np

In [52]:
# using dictionary
data={
    "name":['suryansh','arnab','sambhav'],
    'age':[21,20,20],
    'city':['ngp','ngp','npg']
}
df1=pd.DataFrame(data)

In [53]:
# using list
data_list=[['suryansh',21,'ngp'],
           ['arnab',20,'ngp'],
           ['sambhav',20,'ngp']]
# pd.DataFrame(data_list)
columns=['name','age','city']
df2=pd.DataFrame(data_list,columns=columns)

## selection and indexing of columns

In [54]:
df2[['name','city']]

       name city
0  suryansh  ngp
1     arnab  ngp
2   sambhav  ngp

## Creating new column

In [55]:
df2['Designation']=['student1','student2','student3']

In [56]:
df2

       name  age city Designation
0  suryansh   21  ngp    student1
1     arnab   20  ngp    student2
2   sambhav   20  ngp    student3

## removing columns

In [57]:
df2.drop('Designation',axis=1)

       name  age city
0  suryansh   21  ngp
1     arnab   20  ngp
2   sambhav   20  ngp

In [58]:
df2

       name  age city Designation
0  suryansh   21  ngp    student1
1     arnab   20  ngp    student2
2   sambhav   20  ngp    student3

In [59]:
#inplace: if you want to do something in original dataframe
df2.drop('Designation',axis=1,inplace=True)
df2

       name  age city
0  suryansh   21  ngp
1     arnab   20  ngp
2   sambhav   20  ngp

In [60]:
df2.drop(0,axis=0)

      name  age city
1    arnab   20  ngp
2  sambhav   20  ngp

In [61]:
df2.loc[[0,1]]

       name  age city
0  suryansh   21  ngp
1     arnab   20  ngp

In [62]:
df2.iloc[[0,1]]

       name  age city
0  suryansh   21  ngp
1     arnab   20  ngp

In [63]:
df2.loc[[0,1]][['name','city']]

       name city
0  suryansh  ngp
1     arnab  ngp

## conditional selection

In [ ]:
# select only age>20 and they are from ngp
# df2[(df2["age"]>20) & (df2["city"]=='ngp')]
df2[(df2.age>20) & (df2.city=='ngp')]

       name  age city
0  suryansh   21  ngp

## Finding Missing Data

In [73]:
data=[['suryansh',21,np.nan],
           ['arnab',np.nan,'ngp'],
           ['sambhav',20,'ngp']]
columns=['name','age','city']
df=pd.DataFrame(data,columns=columns)
df

       name   age city
0  suryansh  21.0  NaN
1     arnab   NaN  ngp
2   sambhav  20.0  ngp

In [75]:
df.isna()

    name    age   city
0  False  False   True
1  False   True  False
2  False  False  False

In [76]:
df.isna().sum()

name    0
age     1
city    1
dtype: int64

In [77]:
#to check if any col do not have null value
df.isna().any()

name    False
age      True
city     True
dtype: bool

In [ ]:
# row wise
df.dropna()

      name   age city
2  sambhav  20.0  ngp

In [80]:
# thresh : it set thresold for non null values so the row is not droped .
df.dropna(thresh=2)

       name   age city
0  suryansh  21.0  NaN
1     arnab   NaN  ngp
2   sambhav  20.0  ngp

In [ ]:
# column wise
df.fillna(0)

       name   age city
0  suryansh  21.0    0
1     arnab   0.0  ngp
2   sambhav  20.0  ngp

In [83]:
values={'age':20,'city':'ngp'}
df.fillna(value=values)

       name   age city
0  suryansh  21.0  ngp
1     arnab  20.0  ngp
2   sambhav  20.0  ngp