In [6]:
import pandas as pd

# Employee DataFrame
employee = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
    "name": ["Rahul", "Priya", "Amit", "Sneha"],
    "department": ["IT", "HR", "Finance", "Marketing"]
})

# Salary DataFrame
salary = pd.DataFrame({
    "emp_id": [1, 2, 3, 4,5],
    "salary": [50000, 45000, 60000, 55000,40000],
    "bonus": [5000, 4000, 6000, 5500,4000]
})

In [7]:
#merge : default inner -> based on common ids 

pd.merge(employee,salary,on='emp_id',how='inner')

   emp_id   name department  salary  bonus
0       1  Rahul         IT   50000   5000
1       2  Priya         HR   45000   4000
2       3   Amit    Finance   60000   6000
3       4  Sneha  Marketing   55000   5500

In [ ]:
# outer->based on total number of rows adding both
pd.merge(employee,salary,on='emp_id',how='outer')

   emp_id   name department  salary  bonus
0       1  Rahul         IT   50000   5000
1       2  Priya         HR   45000   4000
2       3   Amit    Finance   60000   6000
3       4  Sneha  Marketing   55000   5500
4       5    NaN        NaN   40000   4000

In [9]:
# left -> based on the first table ids , final no. of row == row in first dtaframe
pd.merge(employee,salary,on='emp_id',how='left')

   emp_id   name department  salary  bonus
0       1  Rahul         IT   50000   5000
1       2  Priya         HR   45000   4000
2       3   Amit    Finance   60000   6000
3       4  Sneha  Marketing   55000   5500

In [10]:
# right -> based on the second table ids , final no. of row == row in 2nd dtaframe
pd.merge(employee,salary,on='emp_id',how='right')

   emp_id   name department  salary  bonus
0       1  Rahul         IT   50000   5000
1       2  Priya         HR   45000   4000
2       3   Amit    Finance   60000   6000
3       4  Sneha  Marketing   55000   5500
4       5    NaN        NaN   40000   4000

## concatination

In [11]:

# First DataFrame
df1 = pd.DataFrame({
    "Name": ["Amit", "Rahul"],
    "Age": [22, 24]
})

# Second DataFrame
df2 = pd.DataFrame({
    "Name": ["Priya", "Sneha"],
    "Age": [23, 25]
})

In [ ]:
# default just add based on col 
pd.concat([df1,df2])

    Name  Age
0   Amit   22
1  Rahul   24
0  Priya   23
1  Sneha   25

In [13]:
pd.concat([df1,df2],axis=1)

    Name  Age   Name  Age
0   Amit   22  Priya   23
1  Rahul   24  Sneha   25

## Joining 2 dataframe

In [32]:
import pandas as pd

# First DataFrame
df1 = pd.DataFrame(
    {
        "names": ["suryansh",'sumit','tejas','tiwari']
    },
    index=[1, 2, 3, 4]
)

# Second DataFrame
df2 = pd.DataFrame(
    {
        "score2": [80, 89, 90, 60]
    },
    index=[2, 3, 4, 5]
)

print(df1)
print(df2)

      names
1  suryansh
2     sumit
3     tejas
4    tiwari
   score2
2      80
3      89
4      90
5      60

In [36]:
df1.join(df2)

      names  score2
1  suryansh     NaN
2     sumit    80.0
3     tejas    89.0
4    tiwari    90.0